<div class="container">
    <div class="row clearfix">
        <div class="col-md-12">
            <div class="row clearfix center-block centered">
                <h1 class="page-header">
                    Личный кабинет
                </h1>
            </div>
            <?php echo($this->partial('profile-partials/tabs-menu.phtml')); ?>

            <form id="frm" class="form-validator edit helper" action="<?php echo($this->easyUrl(array('action' => 'edit', 'id' => $getEdit ['id']))); ?>" method="post" enctype="multipart/form-data">
                <div class="row clearfix center-block">
                    <h4>
                        <!--<a href="<?php echo $this->easyUrl(array('controller' => 'adverts', 'action' => 'index', 'type' => $getEdit ['type'])); ?>">Назад</a>&nbsp;&nbsp;-->Редактировать
                    </h4>
                </div>
                <div class="row clearfix">
                    <?php /*
                    <div class="form-group col-sm-12">
                        <label for="section" class="col-sm-2 control-label">Тип</label>
                        <div class="col-sm-10">
                            <select name="type_id" class="form-control">
                                <?php foreach ($getType as $item): ?>
                                    <option value="<?php echo($item['id']); ?>"<?php echo(($item['id'] == $getEdit['type']) ? ' selected="selected"' : ''); ?>><?php echo($item['name']); ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    */ ?>
                    <input type="hidden" name="type_id" value="<?php echo $getEdit ['type']; ?>" />

                    <div class="form-group col-sm-12">
                        <label for="section" class="col-sm-2 control-label">Раздел</label>
                        <div class="col-sm-10 selectpicker-holder">
                            <select class="form-control category selectpicker" id="tadv-rubr" name="category_id">
                                <?php echo($this->partial('admin/catalog/category/edit-category-select.phtml',
                                    array('categoryList' => $getCategory, 'tab' => '', 'disabled' => true, 'parent_id' => $getEdit['category'])));?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group col-sm-12">
                        <label for="title" class="col-sm-2 control-label">Заголовок</label>
                        <div class="input-holder col-sm-10">
                            <input class="form-control" maxlength="50" id="tadv-title" value="<?php echo $getEdit['name']; ?>" name="name" type="text" placeholder="Введите заголовок обьявления"/>
                            <span class="errors">* Заполните обязательное поле</span>
                        </div>
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="description-short" class="col-sm-2 control-label">Краткое описание</label>
                        <div class="input-holder col-sm-10">
                            <input id="description-short" name="description_short" type="text" value="<?php echo $getEdit['description_short']; ?>" class="form-control">
                        </div>
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="description-full" class="col-sm-2 control-label">Полное описание</label>
                        <div class="input-holder col-sm-10">
                            <textarea id="description-full" class="form-control" name="description_full" cols="30" rows="10"><?php echo $getEdit['description_full']; ?></textarea>
                        </div>
                    </div>

                    <div class="form-group col-sm-12">
                        <label for="img" class="col-sm-2 control-label">Изображение</label>
                        <div class="col-sm-10">
                            <div class="wrap img">
                                <?php echo $this->partial('profile-partials/gallery-upload-box.phtml', array('getGallery' => $getGallery, 'getEdit' => $getEdit)); ?>
                            </div>
                        </div>
                    </div>

                    <div class="form-group col-sm-12">
                        <label class="col-sm-2 control-label">Базовая цена</label>
                        <div class="form-group col-sm-6">
                            <input class="form-control" onkeypress="return isNumberKey(event)" name="price" id="tadv-price" value="<?php echo $getEdit['price']; ?>" type="text" />
                        </div>
                        <div class="form-group col-sm-1">
                            <span class="help-block">грн.</span>
                        </div>
                        <div class="form-group col-sm-1">
                            <label for="for" class="col-sm-4 control-label">За</label>
                        </div>
                        <div class="col-sm-2 selectpicker-holder">
                            <select name="unit_type" class="form-control small selectpicker">
                                <?php foreach ($getUnitTypes as $item): ?>
                                    <option value="<?php echo($item['id']); ?>"<?php echo(($item['id'] == $getEdit['unit_type']) ? ' selected="selected"' : ''); ?>><?php echo($item['shortname']); ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
    <!--
                    <div class="form-group col-sm-12">
                        <div class="form-group col-sm-6">
                            <div class="row clearfix">
                                <div class="form-group col-sm-12">
                                    <div class="col-sm-1"><input id="fund" type="radio" name="s-f" class="form-control"></div>
                                    <div class="col-sm-2"><label for="fund" class="col-sm-4 control-label">Фонд развития</label></div>
                                    <div class="col-sm-8">
                                        <input class="form-control" onkeypress="return isNumberKey(event)" name="price_fond" id="tadv-price" value="<?php echo $getEdit['price_fond']; ?>" type="text"/>
                                    </div>
                                    <div class="col-sm-1"><span class="help-block">грн</span></div>
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="form-group col-sm-12">
                                    <div class="col-sm-1"><input id="sale" type="radio" name="s-f" class="form-control"></div>
                                    <div class="col-sm-2"><label for="sale" class="col-sm-4 control-label">Размер скидки</label></div>
                                    <div class="col-sm-8">
                                        <input class="form-control" onkeypress="return isNumberKey(event)" name="discount" id="tadv-price" value="<?php echo $getEdit['discount']; ?>" type="text"/>
                                    </div>
                                    <div class="col-sm-1"><span class="help-block">грн</span></div>
                                </div>
                            </div>
                        </div>
                    </div>
    -->
                    <div id="item-accessible">
                        <div class="form-group col-sm-12">
                            <label for="img" class="col-sm-2 control-label">Товар доступен</label>
                            <div class="row input-holder col-sm-10">
                                <div class="col-sm-3">
                                    <div class="input-append date">
                                        <input name="date_from[]" class="span2 datepicker" size="16" type="text" value="<?php echo !empty($getDate[0]['date_from']) ? date('d.m.Y', strtotime($getDate[0]['date_from'])) : ''; ?>" />
                                        <span class="add-on"><i class="icon-th"></i></span>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group col-sm-12">
                                        <div class="input-append date">
                                            <input name="date_to[]" class="span2 datepicker" size="16" type="text" value="<?php echo !empty($getDate[0]['date_to']) ? date('d.m.Y', strtotime($getDate[0]['date_to'])) : ''; ?>" />
                                            <span class="add-on"><i class="icon-th"></i></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <?php if ( sizeof($getDate) > 1 ): ?>
                            <?php for ( $i = 1, $cnt = sizeof($getDate);$i < $cnt;$i++ ): ?>
                                <div class="form-group col-sm-12">
                                    <label for="img" class="col-sm-2 control-label"></label>
                                    <div class="row input-holder col-sm-10">
                                        <div class="col-sm-3">
                                            <div class="input-append date">
                                                <input name="date_from[]" class="span2 datepicker" size="16" type="text" value="<?php echo !empty($getDate[$i]['date_from']) ? date('d.m.Y', strtotime($getDate[$i]['date_from'])) : ''; ?>" />
                                                <span class="add-on"><i class="icon-th"></i></span>
                                            </div>
                                        </div>
                                        <div class="col-sm-3">
                                            <div class="form-group col-sm-12">
                                                <div class="input-append date">
                                                    <input name="date_to[]" class="span2 datepicker" size="16" type="text" value="<?php echo !empty($getDate[$i]['date_to']) ? date('d.m.Y', strtotime($getDate[$i]['date_to'])) : ''; ?>" />
                                                    <span class="add-on"><i class="icon-th"></i></span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-1"><a href="#" class="date-remove"><span style="display: block" class="glyphicon glyphicon-remove"></span></a></div>
                                    </div>
                                </div>
                            <?php endfor;?>
                        <?php endif; ?>
                    </div>

                    <div class="form-group col-sm-12">
                        <div class="col-sm-2"></div>
                        <div class="row input-holder col-sm-10">
                            <div class="col-sm-6">
                                Если Вы не укажете ни одной даты - будет показано, что товар доступен всегда.
                                <span class="help-block"><a class="more-dates" href="#">Еще даты</a></span>
                            </div>
                        </div>
                    </div>


                    <div class="col-sm-12 text-center">
                        <a onclick="$(this).closest('form').submit();" class="btn btn-default btn-success" href="#">Редактировать</a>
                    </div>

                    <input type="hidden" name="location" value="0">
                    <input type="hidden" name="edit-form" value="0">
                    <input type="hidden" name="validator" value="<?php echo($this->easyUrl(array('action' => 'validator'))); ?>">
                    <input type="hidden" name="load_options" value="<?php echo($this->easyUrl(array('action' => 'load-options'))); ?>">
                    <input type="hidden" name="require-url" value="<?php echo $this->easyUrl(array('action' => 'get-fields')); ?>">
                    <input type="hidden" name="location_url" value="<?php echo($this->easyUrl(array('action' => 'getCity'))); ?>">
                </div>
            </form>
        </div>
    </div>
</div>