<fieldset style='border:1px dotted #5CB85C; border-radius:6px;'>
    <legend style='color:#5CB85C; font-size:14pt; font-weight:bold; padding:5px;'>Кооператив: Донбас-Карпати</legend>
    <table width='100%' cellpadding='3' cellspacing='3'>
        <tr valign='top'>
            <td style='background-color:f5f5f7;'>
                <fieldset style='border:1px dotted #5CB85C; border-radius:6px;'>
                    <legend style='color:#5CB85C; font-size:12pt; font-weight:bold; padding:5px;'> ОБГОВОРЕННЯ: Тема обговорення 3...</legend>
                    <div>
                        <input type='text' placeholder='Додати питання для обговорення...' style='width:85%;'>
                        <input type='submit' value=' Додати '>
                    </div>
                    <fieldset style='border:1px dotted #5CB85C; border-radius:6px;'>
                        <legend style='color:#5CB85C; font-size:12pt; font-weight:bold; padding:5px;'>Питання для обговорення</legend>
                        <table style='width:100%; font-size:8pt; color:fff;text-align:center; padding:0px;'>
                            <tr style='background-color:#5cb85c;'>
                                <td>№</td>
                                <td>Питання / пропозиція</td>
                                <td>Проголосувало</td>
                                <td>Моя / середня<br>оцінка</td>
                            </tr>
                            <tr style='color:#333;'>
                                <td>1.</td>
                                <td style='text-align:left;'>Питання / пропозиція перше(а)...</td>
                                <td>9/20</td>
                                <td>+4 / +4.5</td>
                            </tr>
                            <tr style='color:#333;'>
                                <td>2.</td>
                                <td style='text-align:left;'>Питання / пропозиція друге(а)...</td>
                                <td>0/20</td>
                                <td> голосувати </td>
                            </tr>
                            <tr style='color:#333;'>
                                <td>3.</td>
                                <td style='text-align:left;'>Питання / пропозиція трете(я)...</td>
                                <td>0/20</td>
                                <td> голосувати </td>
                            </tr>
                        </table>
                    </fieldset>
                    <fieldset style='border:1px dotted #5CB85C; border-radius:6px; font-size:8pt;'>
                        <legend style='color:#5CB85C; font-size:12pt; font-weight:bold; padding:5px;'>Обговорення 1 питання...</legend>
                        <table width='100%' style='font-size:8pt;'>
                            <tr valign='top'>
                                <td width='15%'>Сітник Андрій</td>
                                <td style='background:#fff; padding:2px;'>
                                    <div>Дідтримую на всі 100%</div>
                                </td>
                                <td width='50px'>
                                    +5 (+5)
                                </td>
                            </tr>
                            <tr valign='top'>
                                <td width='15%'>Денис</td>
                                <td style='background:#fff; padding:2px;'>
                                    <div>і я підтримую, хоча є зауваження....</div>
                                </td>
                                <td width='50px'>
                                    +4.5 (<a href=''>оцінити</a>)
                                </td>
                            </tr>
                            </tr>
                        </table>
                        <div style='margin-top:10px; border-top:1px dotted; border-bottom:1px dotted; margin:10px;'>
                            <div style='margin:10px;'>
                                <input type='text' placeholder='Додати свій коментар...' style='width:80%;'>
                                <input type='submit' value=' Додати '>
                            </div>
                        </div>
                        <table width='100%'>
                            <tr>
                                <td>
                                    <table style='font-size:7pt;'>
                                        <tr>
                                            <td><input type='radio'></td>
                                            <td><input type='radio'></td>
                                            <td><input type='radio'></td>
                                            <td><input type='radio'></td>
                                            <td><input type='radio'></td>
                                            <td><input type='radio'></td>
                                            <td><input type='radio'></td>
                                            <td><input type='radio'></td>
                                            <td><input type='radio'></td>
                                            <td><input type='radio'></td>
                                            <td><input type='radio'></td>
                                        </tr>
                                        <tr>
                                            <td style='text-align:center;'>-5</td>
                                            <td style='text-align:center;'>-4</td>
                                            <td style='text-align:center;'>-3</td>
                                            <td style='text-align:center;'>-2</td>
                                            <td style='text-align:center;'>-1</td>
                                            <td style='text-align:center;'>0</td>
                                            <td style='text-align:center;'>+1</td>
                                            <td style='text-align:center;'>+2</td>
                                            <td style='text-align:center;'>+3</td>
                                            <td style='text-align:center;'>+4</td>
                                            <td style='text-align:center;'>+5</td>
                                        </tr>
                                    </table>
                                </td>
                                <td>
                                    <input type='submit' value='ОЦІНИТИ' style='padding:20px 20px 20px 20px;'>
                                </td>
                            </tr>
                        </table>
                    </fieldset>			    
                    <fieldset style='border:1px dotted #5CB85C; border-radius:6px; font-size:8pt;'>
                        <legend style='color:#5CB85C; font-size:12pt; font-weight:bold; padding:5px;'>Обговорення 2 питання...</legend>
                        <table width='100%' style='font-size:8pt;'>
                            <tr valign='top'>
                                <td width='15%'>Сітник Андрій</td>
                                <td style='background:#fff; padding:2px;'>
                                    <div>Дідтримую на всі 100%</div>
                                </td>
                                <td width='50px'>
                                    +5 (4.5)
                                </td>
                            </tr>
                            <tr valign='top'>
                                <td width='15%'>Денис</td>
                                <td style='background:#fff; padding:2px;'>
                                    <div>і я підтримую, хоча є зауваження....</div>
                                </td>
                                <td width='50px'>
                                    +4 (<a href=''>оцінити</a>)
                                </td>
                            </tr>
                            </tr>
                        </table>
                        <div style='margin-top:10px; border-top:1px dotted; border-bottom:1px dotted; margin:10px;'>
                            <div style='margin:10px;'>
                                <input type='text' placeholder='Додати свій коментар...' style='width:80%;'>
                                <input type='submit' value=' Додати '>
                            </div>
                        </div>
                        <table width='100%'>
                            <tr>
                                <td>
                                    <table style='font-size:7pt;'>
                                        <tr>
                                            <td><input type='radio'></td>
                                            <td><input type='radio'></td>
                                            <td><input type='radio'></td>
                                            <td><input type='radio'></td>
                                            <td><input type='radio'></td>
                                            <td><input type='radio'></td>
                                            <td><input type='radio'></td>
                                            <td><input type='radio'></td>
                                            <td><input type='radio'></td>
                                            <td><input type='radio'></td>
                                            <td><input type='radio'></td>
                                        </tr>
                                        <tr>
                                            <td style='text-align:center;'>-5</td>
                                            <td style='text-align:center;'>-4</td>
                                            <td style='text-align:center;'>-3</td>
                                            <td style='text-align:center;'>-2</td>
                                            <td style='text-align:center;'>-1</td>
                                            <td style='text-align:center;'>0</td>
                                            <td style='text-align:center;'>+1</td>
                                            <td style='text-align:center;'>+2</td>
                                            <td style='text-align:center;'>+3</td>
                                            <td style='text-align:center;'>+4</td>
                                            <td style='text-align:center;'>+5</td>
                                        </tr>
                                    </table>
                                </td>
                                <td>
                                    <input type='submit' value='ОЦІНИТИ' style='padding:20px 20px 20px 20px;'>
                                </td>
                            </tr>
                        </table>
                    </fieldset>			    
                </fieldset>
            </td>
            <td width='200px' style='background-color:f5f5f7;'>
                <div style='color:5cb85c; border-bottom:1px solid #5cb85c;font-weight:bold; padding:3px; margin-bottom:5px;'>Дідменю кооперативу</div>
                <a href='javascript:;' class='leftMenu'>Новини</a>
                <a href='javascript:;' class='leftMenu'>Члени кооперативу</a>
                <a href='javascript:;' class='leftMenu'><b>Обговорення</b></a>
                <a href='javascript:;' class='leftMenu'>Документи</a>
                <a href='javascript:;' class='leftMenu'> . . . </a>
            </td>
        </tr>
    </table>
</fieldset>