<form class="type-form-validator add" action="<?php echo($this->easyUrl(array('action' => 'type-add'))); ?>" method="post">
  <fieldset>
    <legend>Добавление типа</legend>
    <div class="control-group">        
        <label class="control-label">Название</label>
        <div class="controls">
            <input type="text" name="name" placeholder="Введите текст…" maxlength="10" value="">
        </div>
    </div>
    <div class="form-actions">
      <button type="submit" class="btn btn-primary">Сохранить</button>
      <a class="btn" href="<?php echo($this->easyUrl(array('action' => 'type'))); ?>">Отменить</a>
    </div>
  </fieldset>
  <input type="hidden" name="add-form" value="0">
  <input type="hidden" name="validator" value="<?php echo($this->easyUrl(array('action' => 'type-validator'))); ?>">
</form>
