<?php echo $this->form; ?>
<fieldset style='border:1px dotted #5CB85C; border-radius:6px; text-align:center;'>
    <legend style='color:#5CB85C; font-size:14pt; font-weight:bold; padding:5px;'>Товариства</legend>
    <table style='width:99%; margin-bottom:20px;'>
        <tr>
            <td style=' text-align:left;'>
                <select>
                    <option>всі</option>
                    <option>групи</option>
                    <option>фірми</option>
                    <option>кооперативи</option>
                </select>
                <input type='search' name='googlesearch' style='width:70%;'>
                <input type='button' style='width:24px; height:22px; background-image:url(/cms/assets/image/199dfaf69bfc4809346f4368017268d6x.jpg);background-size: 19px 19px;'>
            </td>
            <td style='width:25%;text-align:right;'>
                <a href='/forum/group/add/'>
                    <span style='display:inline-block; width:200px; text-align:center; color:#ffffff; background-color:#5cb85c; padding:3px;'>Створити групу</span>
                </a>
            </td>
        </tr>
    </table>
    <div style='margin:auto;width:98.8%;'>
        <?php if(is_array($this->groupList)): ?>
        <?php foreach ($this->groupList as $key => $value): ?>
            <table class='linkButton'>
                <tr valign='top'>
                    <td width='140px'>
                        <img src='<?php echo $value['avatar_url']; ?>' style='float:left; margin-right:20px; max-width:150px;'>
                    </td>
                    <td>
                        <div style='margin:1px; padding:1px; font-size:12pt;'><a href='
                                <?php echo $this->url('forum/group-view', array('id_group' => $value['id'])); ?>'>
                                <b><?php echo $value['type_organization_title'] . ':   ' . $value['title']; ?></b></a></div>
                        <div>&nbsp;</div>
                        <div><?php echo $value['description'] ?></div>
                    </td>
                </tr>
                <tr>
                    <td colspan=2 style='text-align:right; border-top:1px dotted;'>
                        Рейтинг: 3.5,  Учасників: 200, Остання дія: 01.04.2014 16:41
                    </td>
                </tr>
                <tr><td>
                        <a href="<?php echo $this->url('forum/group-edit', array('id' => $value['id'])); ?>" style="padding-right: 50px ">EDIT</a>
                        <a href="<?php echo $this->url('forum/group-delete', array('id' => $value['id'])); ?>" >DELETE</a>
                    </td></tr>
            </table>	
        <?php endforeach; ?>
        <?php endif;?>
<!--		    <table class='linkButton'>
            <tr valign='top'>
                <td width='140px'>
                <img src='sponser-logo-4.jpg' style='float:left; margin-right:20px; max-width:150px;'>
                </td>
                <td>
                    <div style='margin:1px; padding:1px; font-size:12pt;'><a href=''>Фірма: Hewlett Packard</a></div>
                    <div>Україна, Івано-Франківськ</div>
                    <div>Додаткова інформація...</div>
                </td>
            </tr>
            <tr>
                <td colspan=2 style='text-align:right; border-top:1px dotted;'>
                    Рейтинг: 4.8,  Учасників: 34000, Остання дія: 01.04.2014 16:41
                </td>
            </tr>
        </table>		    -->
    </div></div>
</fieldset>
