<div class="container">
    <div class="row clearfix">
        <div class="col-md-12">
            <div class="row clearfix center-block centered">
                <h1 class="page-header">
                    Личный кабинет
                </h1>
            </div>
            <?php echo($this->partial('profile-partials/tabs-menu.phtml')); ?>

            <div class="tab-content">
                <div id="tab3">
                    Изменения успешно сохранены
                    <input type="hidden" class="settings-url" value="/profile/settings" />
                </div>
            </div>
        </div>
    </div>
</div>