<div class="container reg-container">
    <div class="row clearfix">
        <div class="col-md-12 separation">
            <div class="row clearfix center-block centered">
                <h1 class="page-header">
                    Вход
                </h1>
                <span id="vb_errors" class="errors" style="color: red"><?php if (!empty($error)) echo $error;?></span>
                <p>
                    Введите данные, указанные при <a href="<?php echo($this->easyUrl(array('module'=>'profile','controller'=>'registration')));?>">регистрации</a>.
                </p>
                <p>
                    Если Вы не помните свой пароль, воспользуйтесь формой
                    <a href="<?php echo($this->easyUrl(array('module' => 'profile', 'controller' => 'forgot'))); ?>">Напоминания пароля</a>.
                </p>
            </div>
            <div class="row clearfix">
                <form method="post" action="<?php echo($this->easyUrl(array('module' => 'profile', 'controller' => 'login'))); ?>" class="form-horizontal login-form" role="form">
                    <div class="form-group col-sm-12">
                        <label for="e-mail" class="col-sm-4 control-label">Электронная почта</label>
                        <div class="input-holder col-sm-8 ">
                            <input name="username" id="e-mail" type="email" class="form-control">
                            <span class="errors">Укажите действительный адрес почты</span>
                        </div>
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="pasw" class="col-sm-4 control-label">Пароль</label>
                        <div class="input-holder col-sm-8">
                            <input name="password" id="pasw" type="password" class="form-control">
                            <span class="errors">Введите пароль</span>
                        </div>
                    </div>
                    <div class="form-group col-sm-12">
                        <label class="col-sm-4 control-label" for="captcha">Пожалуйста, докажите, что вы человек</label>
                        <div class="input-holder col-sm-8">
                            <?php
                            echo $this->formRow($captcha->get('captcha')->setAttribute('class' , 'form-control'));
                            ?>
                            <span class="errors">* значение Captcha неверно</span>
                        </div>
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="saveme" class="col-sm-4 control-label">Запомнить меня</label>
                        <div class="input-holder col-sm-8">
                            <input id="saveme" name="saveme" type="checkbox" value="1" class="form-control customStyled" />
                        </div>
                    </div>

                    <div class="col-sm-12 centered">

                        <div class="center-block text-center">
                            <a class="btn btn-default btn-success" onclick="$(this).closest('form').submit()">Отправить</a>
                            <input type="hidden" name="referrer" value="<?php echo $referrer; ?>">
                            <input type="hidden" name="validator" value="<?php echo($this->easyUrl(array('module' => 'profile','controller' => 'login', 'action' => 'validator'))); ?>">
                            <input type="hidden" name="login-form" value="0">
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>