<?php if ((isset($getGallery) && is_array($getGallery)) && !empty($getGallery[0])): ?>

    <a href="<?php echo ($item['url']); ?>" data-lightbox="place-gallery">
        <img class="gal-img" src="<?php echo($getGallery[0]['slider']['small']); ?>" alt="#"/></a>

    <?php /*

    <div class="galleryka-holder carousel1 item-gallery">
        <div class="galleryka">
            <div class="gholder">
                <a class="btn-prev" href="#"><span></span></a>
                <a class="btn-next" href="#"><span></span></a>
<!--                <a class="fullscreen" href="#"></a>-->
                <div class="gmask-center">
                    <div class="gmask flscrn">
                        <ul>
                            <?php foreach ($getGallery as $item) { ?>
                                <li class="c1">
                                    <a href="<?php echo ($item['url']); ?>" data-lightbox="place-gallery">
                                        <img class="gal-img" src="<?php echo($item['slider']['medium']); ?>" alt="#"/></a>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="pagination">
                <ul>
                    <?php foreach ($getGallery as $item) { ?>
                        <li><a href="#"><img src="<?php echo($item['slider']['small_gallery']); ?>" alt="#"/></a></li>

                    <?php } ?>
                </ul>
            </div>
        </div>
    </div>

 */ ?>
<?php else: ?>
    <span class="glyphicon glyphicon-camera"></span>
<?php endif; ?>