<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php $this->headTitle($this->siteName())->setSeparator(' - ')->setAutoEscape(false);
        echo($this->headTitle());
        ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <!-- styles and js -->
        <?php
        $this->headLink(/* array(
                  'rel' => 'shortcut icon',
                  'type' => 'image/png',
                  'href' => $this->basePath() . '/img/favicon.png'
                  ) */)
                ->appendStylesheet($this->basePath() . '/cms/assets/css/profile-layout.css');
            echo($this->headLink() . "\n");
        ?>
    </head>
    <body>
<?php echo($this->partial('application/layout/header')); ?>
    <center>
        <table style='width:98%;'>
            <tr valign='top'>
                <td style='width:200px; text-align:center;'><img src='Cast-Icon.png' style='width:175px;'>
                <td>
                    <div style='font-size:16pt; font-weight:bold; border-bottom:1px dotted; margin-top:15px;'>Прізвище Ім'я По-батькові</div>
                    <div style='font-size:10pt; margin: 5px 5px 5px 0px;'>
                        <div>Україна, Івано-Франківськ</div>
                        <div>E-mail: <a href='mailto:mail@mail.com'>mailto:mail@mail.com</a></div>
                        <div>Моб.тел.: +38(0XX) XXX-XX-X1</div>
                        <div><a href='javascript:;' class='linkMore'>Відобразити повну інформацію &#9660;</a></div>	
                    </div>
                </td>
            </tr>
            <tr valign='top'>
                <td style='width:200px'>
                    <div style='color:#ffffff; border:1px dotted #5CB85C; background-color:#5CB85C; padding:5px 5px 5px 10px; margin-top:10px; box-shadow: 3px -3px 3px #f0f0f0;'>Меню</div>
                    <a href='javascript:;' class='leftMenu'>Моя сторінка</a>
                    <a href='javascript:;' class='leftMenu'>Новини / події</a>
                    <a href='javascript:;' class='leftMenu'>Друзі</a>
                    <a href='<?php echo $this->url('forum/default', array('controller' => 'group','action' => 'list')); ?>' class='leftMenu'>Групи / кооп. / фірми</a>
                    <a href='javascript:;' class='leftMenu'>Повідомлення</a>
                    <div style='height:2px; background-color:#333333;'></div>
                    <a href='javascript:;' class='leftMenu'>Документи</a>
                    <a href='javascript:;' class='leftMenu'>Фото</a>
                    <a href='javascript:;' class='leftMenu'>Відео</a>
                </td>
                <td>
                    <div style='color:#ffffff; border:1px dotted #5CB85C; background-color:#5CB85C; padding:5px; margin-top:10px; box-shadow: 3px -3px 3px #f0f0f0;'>
                        <a href='javascript:;' class='mainMenu'>Оголошення</a>
                        <a href='javascript:;' class='mainMenu'>Статистика</a>
                        <a href='javascript:;' class='mainMenu'>Відгуки / Оцінки</a>
                        <a href='javascript:;' class='mainMenu'>Рейтинг</a>
                        <a href='javascript:;' class='mainMenu'>Профіль</a>
                    </div>
<?php echo($this->content); ?>
                </td>
            </tr>
        </table>
    </center>        
    <!-- /container -->
<?php echo($this->partial('application/layout/footer')); ?>
    
            
    <?php $this->headScript()
                 ->prependFile($this->basePath() . '/js/libs/jquery-1.8.1.min.js');
        echo($this->headScript() . "\n");
        echo($this->inlineScript()); 
    ?>
</body>
</html>