<table width='100%'>
    <tr valign='top'>
        <td width='150px' style='font-size:8pt;text-align:center; border:1px dotted;'>
            <div style='font-size:7pt; text-align:right;'>+3.5 </div>
            <img src='http://wenet.pu.if.ua/tmp/project/vote/data/img/user.png' style='width:100px;'>
            <div style='font-size:8pt; padding:5px 0px 5px 5px;'>
                <b><?php echo $this->commentData['firstname'].'  '.$this->commentData['lastname'];?></b>
                <!-- <div style='font-size:7pt; padding-top:3px;'> створено</div> -->
            </div>
        </td>
        
        <td style='border:1px dotted; padding:0px;'>
            <div style='min-height:120px; padding:5px;'><?php echo $this->commentData['comment'];?></div>
            <div style='text-align:right; background:#f5f5f5; padding: 3px 25px 3px 25px; font-size:8pt; color:#333333; border-top:1px dotted;'>
                <b>Дата:</b> <?php echo  $this->commentData['creation'];?> | 
                <b>Оцінка:</b> +3.5 
                <!-- <a href='' style='color:#333333;'><b>Прокоментувати</b></a>  -->
            </div>
        </td>
    </tr>
</table>