<div class="wrapper sms-page">
    <div class="wrapper-center">
        <div class="subnav">
            <div class="holders group">
                <a class="sbmt-gr active" href="#">Сообщения</a>
                <a class="sbmt-gr" href="#">Архив</a>

<!--                <select class="select-filtr" id="filtr" name='filtr'>-->
<!--                    <option value='option-1'>по дате, сначала новые</option>-->
<!--                    <option value='option-2'>option2</option>-->
<!--                    <option value='option-3'>option3</option>-->
<!--                </select>-->
            </div>
        </div>
        <div class="date-holder">
            <div class="holders">
                <a class="goback" href="<?php echo($this->easyUrl(array('action' => 'index'))); ?>">Вернуться</a>
            </div>
        </div>
        <section class="dialogs">
            <div class="holders group">
                <div class="the-dialog group ">
                    <div class="col1">
<!--                        <img class="ava" src="/img/tmp/avka1.png" alt="#"/>-->
                        <div class="hold">
                            <p class="author"><?php echo $user['name']; ?></p>
                        </div>
                    </div>
                    <?php if ($messagesList) { ?>
                        <div class="col2">
                        <?php foreach ($messagesList as $item) { ?>
                            <?php if ($item['username'] == $item['from_username']) { ?>
                                <div class="author-text"><?php echo $item['text']; ?>
                                    <p class="timing"><span></span><?php echo $item['timestamp']; ?></p>
                                </div>
                            <?php } else { ?>
                                <div class="ansver-holder group">
                                    <div class="ansver">
                                        <span class="timing"><span></span><?php echo $item['timestamp']; ?></span>
                                        <?php echo $item['text']; ?>
                                    </div>
                                </div>
                            <?php } ?>
                        <?php } ?>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </section>
        <section class="sms-adding">
            <div class="holders">
                <div class="sms-form-holder group">
                    <p>Добавить сообщение</p>
                    <form id="frm" class="form-validator add" action="<?php echo($this->easyUrl(array('action' => 'add'))); ?>" method="post" enctype="multipart/form-data">
                        <textarea name="text" id="sms" placeholder="Введите текст сообщения &#8230;"></textarea>
<!--                        <input id="file4" type="file">-->
                        <input type="hidden" name="to_user_id" value="<?php echo $user['id']; ?>">
                        <input type="hidden" name="advert_id" value="<?php echo $advertId; ?>">
                        <input type="hidden" name="add-form" value="0">
                        <input type="hidden" name="validator" value="<?php echo($this->easyUrl(array('action' => 'validator'))); ?>">
                        <a class="sbmt-gr submitIt">Отправить</a>
                    </form>
                </div>
            </div>
        </section>
   </div>
</div>