<div class="container">
    <div class="row clearfix">
        <div class="col-md-12">
            <div class="row clearfix center-block centered">
                <h1 class="page-header">
                    Список пользователей
                </h1>
            </div>

            <ul id="tabs" class="nav nav-tabs">
                <li class="active">
                    <a data-toggle="tab" href="#physical">Физ. лица</a>
                </li>
                <li>
                    <a data-toggle="tab" href="#legal" class="last_tab">Юр. лица</a>
                </li>
            </ul>

            <div class="tab-content pad">
                <div class="tab-pane fade active in" id="physical">
                    <?php if (!empty($usersList [$Model::TYPE_PHYSICAL])): ?>
                        <?php foreach ($usersList [$Model::TYPE_PHYSICAL] as $item): ?>
                            <div class="clearfix pad mar-bot post">
                                <div class="col-sm-12">
                                    <div class="row">

                                        <div class="col-sm-10 row">
                                            <div class="col-sm-12 row">

                                                <div class="col-sm-2 pull-left">
                                                    <div class="col-sm-12 pad">
                                                        <div class="row">
                                                            <div class="col-sm-12 align-left">
                                                                Добавлен
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-sm-12 align-left">
                                                                <span><?php echo $item['date']; ?></span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="col-sm-1 pull-left pad">
                                                    <?php if ( !empty($item ['avatar_img']) ): ?>
                                                        <img class="img-rounded" border="0" width="72" height="72" src="<?php echo $item ['avatar_img']; ?>" alt="" />
                                                    <?php else: ?>
                                                        <img class="img-rounded" border="0" width="72" height="72" src="/img/ava.png" />
                                                    <?php endif; ?>
                                                </div>

                                                <div class="col-sm-8">
                                                    <div class="row">
                                                        <div class="col-sm-12">
                                                            <h4>
                                                                <a href="<?php echo $this->easyUrl(array('module' => 'profile', 'controller' => 'users', 'action' => 'view', 'id' => $item ['id'])); ?>"><?php echo
                                                                        $item['lastname'] . ' ' . $item['firstname'] . ' ' . $item['secondname'];
                                                                ?></a>
                                                            </h4>
                                                        </div>
                                                    </div>

                                                    <div class="row">
                                                        <div class="col-sm-12">
                                                            <?php if (!empty($item ['city'])): ?>
                                                                <ul class="breadcrumb">
                                                                    <li><?php echo $item ['region']; ?></li>
                                                                    <li><?php echo $item ['area']; ?></li>
                                                                    <li class="active"><?php echo $item ['city']; ?></li>
                                                                </ul>
                                                            <?php endif; ?>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>

                                        <div class="col-sm-2">
                                            <div class="row pad text-center">
                                                <span><?php echo($item['phone1']); ?></span>
                                            </div>
                                            <div class="row text-center">
                                                <?php if (!empty($item ['username'])): ?><span><a href="mailto:<?php echo $item['username']; ?>"><?php echo $item['username']; ?></a></span><?php endif;?>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>

                <div class="tab-pane" id="legal">
                    <?php if (!empty($usersList [$Model::TYPE_LEGAL])): ?>
                        <?php foreach ($usersList [$Model::TYPE_LEGAL] as $item): ?>
                            <div class="clearfix pad mar-bot post">
                                <div class="col-sm-12">
                                    <div class="row">

                                        <div class="col-sm-10 row">
                                            <div class="col-sm-12 row">

                                                <div class="col-sm-2 pull-left">
                                                    <div class="col-sm-12 pad">
                                                        <div class="row">
                                                            <div class="col-sm-12 align-left">
                                                                Добавлен
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-sm-12 align-left">
                                                                <span><?php echo $item['date']; ?></span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="col-sm-1 pull-left pad">
                                                    <img src="/img/ava.png" class="img-rounded">
                                                </div>

                                                <div class="col-sm-8">
                                                    <div class="row">
                                                        <div class="col-sm-12">
                                                            <h4>
                                                                <?php if (!empty($item ['name'])): ?>
                                                                    <a href="mailto:<?php echo $item['username']; ?>"><?php echo($item['name']); ?></a>
                                                                <?php else: ?>
                                                                    <a href="mailto:<?php echo $item['username']; ?>"><?php echo($item['username']); ?></a>
                                                                <?php endif;?>
                                                            </h4>
                                                        </div>
                                                    </div>

                                                    <div class="row">
                                                        <div class="col-sm-12">
                                                            <?php if (!empty($item ['city'])): ?>
                                                                <ul class="breadcrumb">
                                                                    <li><?php echo $item ['region']; ?></li>
                                                                    <li><?php echo $item ['area']; ?></li>
                                                                    <li class="active"><?php echo $item ['city']; ?></li>
                                                                </ul>
                                                            <?php endif; ?>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>

                                        <div class="col-sm-2">
                                            <div class="row pad text-center">
                                                <span><?php echo($item['phone1']); ?></span>
                                            </div>
                                            <div class="row text-center">
                                                <?php if (!empty($item ['username'])): ?><span><a href="mailto:<?php echo $item['username']; ?>"><?php echo $item['username']; ?></a></span><?php endif;?>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>


        </div>
    </div>
</div>