<div class="container">
    <div class="row clearfix">
        <div class="col-md-12">
            <div class="row clearfix center-block centered">
                <h1 class="page-header">
                    Личный кабинет
                </h1>
            </div>
            <!-- Nav tabs -->
            <?php echo($this->partial('profile-partials/tabs-menu.phtml')); ?>

            <!-- Tab panes -->
            <div class="row clearfix">
                <div class="col-sm-12">
                    <div class="col-sm-9">

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="row">
                                    <div class="col-sm-12">

                                        <div class="margined">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <h3>Комментарии</h3>
                                                </div>
                                            </div>

                                            <?php echo $this->partial('profile-partials/comments-list.phtml', array('advertComments' => $commentsList, 'userId' => $userId)); ?>

                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>


<?php /*
            <div class="tab-content">
                <div id="comments"> <!--  class="tab-pane fade" -->
                    <?php echo $this->partial('profile-partials/comments-list.phtml', array('advertComments' => $commentsList, 'userId' => $userId)); ?>
                </div>
            </div>

        </div>
    </div>
</div>
 */ ?>