<div class="container">
    <div class="row clearfix">
        <div class="col-sm-12">
            <div class="row clearfix center-block centered">
                <h1 class="page-header">
                    <?php echo($advert['name']); ?>
                </h1>
            </div>
            <div class="row clearfix">
                <div class="col-sm-12">
                    <div class="col-sm-9">
                        <div class="row">

                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="col-sm-12">
                                        <ul class="breadcrumb">
                                            <?php if ( !empty($advert['breadcrumbs']) ): ?>
                                                <?php $last = sizeof($advert ['breadcrumbs']) - 1; foreach ( $advert['breadcrumbs'] as $key => $row ): ?>
                                                    <li<?php echo ($key == $last ? ' class="active"' : '');?>><?php echo $row ['name']; ?></li>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                            <div class="col-sm-12 mar-bot">
                                <div class="col-sm-2">
                                    <?php if (!empty($getGallery [0])) { ?>
                                        <img class="img-rounded" src="<?php echo($this->easyUrl(array('module' => 'application', 'controller' => 'image', 'action' => 'adverts-gallery', 'id' => $getGallery [0] ['id'], 'w' => 72, 'h' => 72, 'crop' => 'y'))) ?>" alt="" />
                                    <?php } else { ?>
                                        <img src="/img/ava.png" class="img-rounded">
                                    <?php } ?>
                                </div>
                                <div class="col-sm-10">
                                    <div class="row">
                                        <div class="col-sm-12  clearfix">
                                            <p class="pull-right">Цена <span><?php echo($advert['price']); ?> <?php echo $advert['currency']; ?>/<?php echo($advert['unit_type']); ?></span></p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <?php echo($advert['description_full']); ?>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <p>Текущая оценка товара: <span><?php echo round($advert ['rating_mark']); ?></span></p>
                                            <p>Проголосовало: <span><?php echo $advert ['rating_users']; ?></span> пользователей</p>
                                        </div>
                                    </div>
                                    <?php // if ( empty($advert ['is_voted']) ): ?>
                                        <div class="row">
                                            <div class="col-sm-12">
                                                Оценить товар:
                                            </div>
                                        </div>
                                        <form method="post" action="<?php echo $this->easyUrl(array('module' => 'profile', 'controller' => 'adverts', 'action' => 'set-rating')); ?>">
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <div class="row">
                                                    <div class="col-sm-12">
                                                        <div class="row">
                                                            <div class="col-sm-3">
                                                                <div class="bfh-slider" data-name="rating" data-value="<?php echo $advert ['rating']; ?>"></div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row col-sm-12 margined">
                                                    <?php if ( isset($_SESSION['profile']->auth['id']) ): ?>
                                                        <a onclick="$(this).closest('form').submit();return false;" class="btn btn-default btn-success" href="#">Отправить</a>
                                                    <?php else: ?>
                                                        <a class="register-request btn btn-default btn-success" href="#">Отправить</a>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        </div>
                                        <input type="hidden" name="id" value="<?php echo $advert ['id']; ?>" />
                                        </form>
                                    <?php // endif; ?>
                                </div>
                            </div>


                        </div>

                        <!-- Comments :BEGIN -->
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="margined">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <h3>Комментарии</h3>
                                                </div>
                                            </div>

                                            <?php echo $this->partial('partials/comments-list.phtml', array('advertComments' => $advertComments, 'userId' => $userId, 'user_fields' => $user_fields)); ?>

                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <h4>Комментарий</h4>
                                                    <?php
                                                    $captcha = $this->formRow($captcha->get('captcha')->setAttribute('class' , 'form-control')->setAttribute('style' , 'width:35%;margin:0 0 10px 0'));
                                                    ?>
                                                    <?php echo $this->partial('partials/comment-add.phtml', array('advert' => $advert, 'parent_id' => 0, 'captcha' => $captcha)); ?>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>




                    </div>

                    <div class="col-sm-3">
                        <div class="row bordered mar-bot">
                            <div class="col-sm-12">
                                <h4>Товар доступен к продаже:</h4>
                                <?php if ( empty($getDates) ): ?>
                                    <p>Всегда</p>
                                <?php else: ?>
                                    <?php foreach ( $getDates as $rec ): ?>
                                        <p><?php echo date('d.m.Y', strtotime($rec ['date_from'])); ?> - <?php echo date('d.m.Y', strtotime($rec ['date_to'])); ?></p>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                                <h4>Продавец:</h4>
                                <p> <a href="<?php echo($this->easyUrl(array('module' => 'profile', 'controller' => 'users', 'action' => 'view', 'id' =>  $advert ['user_id']))); ?>"><?php echo $advert ['user_username']; ?></a></p>
                                <h4>Местонахождение:</h4>
                                <?php if (!empty($advert ['city'])): ?>
                                    <p>
                                        <?php echo $advert ['region']; ?>,
                                        <?php echo $advert ['area']; ?>,
                                        <?php echo $advert ['city']; ?>
                                    </p>
                                <?php endif; ?>
                                <h4>Контакты</h4>
                                <!--<p><?php /*echo $advert ['user_phone1']; */?></p>-->
                            </div>
                        </div>
                    </div>





                </div>
            </div>
        </div>
    </div>



</div>

<?php if ( isset($_SESSION['profile']->auth['id']) ): ?>
    <?php echo $this->partial('popups/comment-add.phtml', array('advert' => $advert, 'parent_id' => 0, 'id' => 0)); ?>
<?php endif; ?>

<!-- Comments :END -->